var searchData = {
    "total": 76,
    "lessons": [{
        "approved": "approved",
        "author_id": 43865,
        "created_at": "2014-01-06T18:02:24Z",
        "draft_version_id": 44903,
        "duration": 719689,
        "first_published_at": "2014-01-15T18:28:58Z",
        "id": 4748,
        "internal_rating": 100,
        "name": "Crochet Swirl Sun Hat | Pt 3",
        "position": 8,
        "published_at": "2014-11-07T23:39:51Z",
        "published_version_id": 42435,
        "saved_at": "2015-05-28T21:46:26Z",
        "short_name": "Crochet Swirl Sun Hat | Pt 3",
        "slug": "diy-crochet-swirl-sun-hat-pt-3",
        "updated_at": "2015-08-19T01:18:16Z",
        "presenter_name": "The Crochet Zombie",
        "meta": {
            "all_keywords": ["advanced", "intermediate", "fall", "winter", "crafts", "Crocheting", "clothes_making", "accessories"],
            "approval_state": "approved",
            "canonical_category": "clothes-making",
            "comments": 21,
            "has_free_promo": false,
            "has_unpublished_changes": true,
            "is_conversation": false,
            "is_third_party_content": false,
            "loves": 31,
            "points": 6,
            "price": 199,
            "project_submissions": 11,
            "published": true,
            "students": 161,
            "views": 891,
            "alt_image_url": null,
            "attachments": 5,
            "card_image_url": "/system/development/files/102296/card/01SwirlSun_09_FinishingOff.mp4.00_35_25_01.Still001.jpg?1429490660",
            "clipped_intro_resource_url": null,
            "duration": 719689,
            "exercises": 2,
            "longDescriptionHTML": "Your toddler\u2019s summer hat is almost complete! If you have already crocheted rounds 1-14, you should be able to see the swirl pattern and the shape of the cap. In the final lesson of this series by The Crochet Zombie, learn how to knit the brim in five easy rounds, bind off, and conceal any loose ends. If you like the finished product, make one in adult size to match!",
            "name": "Crochet Swirl Sun Hat | Pt 3",
            "sections": [{
                "name": "Round 15",
                "duration": 162757,
                "exercises": [{"name": "First Steps"}]
            }, {"name": "Round 16", "duration": 146852, "exercises": []}, {
                "name": "Rounds 17-19",
                "duration": 195790,
                "exercises": [{"name": "Repeats"}]
            }, {"name": "Binding Off", "duration": 214290, "exercises": []}],
            "shortDescription": "Your toddler\u2019s summer hat is almost complete! The final lesson in this series demonstrates how to crochet the brim and tie off any loose ends.",
            "small_card_image_url": "/system/development/files/102296/small_card/01SwirlSun_09_FinishingOff.mp4.00_35_25_01.Still001.jpg?1429490660",
            "still_image_large_original_height": 630,
            "still_image_large_original_width": 1120,
            "still_image_url": "/system/development/files/102296/large_16x9/01SwirlSun_09_FinishingOff.mp4.00_35_25_01.Still001.jpg?1429490660",
            "still_image_url_large_original": "/system/development/files/102296/large_original/01SwirlSun_09_FinishingOff.mp4.00_35_25_01.Still001.jpg?1429490660"
        },
        "author": {
            "id": 43865,
            "first_name": "First43865",
            "display_name": "The Crochet Zombie",
            "teacher_display_name": "The Crochet Zombie",
            "greeting_name": "First43865",
            "username": "thecrochetzombie",
            "param": "thecrochetzombie",
            "title": "Crochet Instructor and Designer",
            "description": "Hi, I am The Crochet Zombie, I am a yarn lover and a designer of crochet items from clothing to decorations and everything in between. I love to be creative and share the things I learn with my friends, fans and family.",
            "avatar": "/system/development/avatars/43865/normal/logo-tcz-square.jpg?1381430861",
            "avatar_square": "/system/development/avatars/43865/square/logo-tcz-square.jpg?1381430861",
            "avatar_large": "/system/development/avatars/43865/large/logo-tcz-square.jpg?1381430861",
            "tip_prompt": ""
        }
    }, {
        "approved": "approved",
        "author_id": 23932,
        "created_at": "2013-10-26T06:14:12Z",
        "draft_version_id": 21127,
        "duration": 372417,
        "first_published_at": "2013-11-27T16:29:59Z",
        "id": 3419,
        "internal_rating": null,
        "name": "Taking Photos in Sun and Shade",
        "position": 20,
        "published_at": "2014-04-02T00:45:24Z",
        "published_version_id": 21080,
        "saved_at": "2015-07-20T10:43:22Z",
        "short_name": "Taking Photos in Sun and Shade",
        "slug": "taking-photos-in-sun-and-shade",
        "updated_at": "2015-12-05T00:23:42Z",
        "presenter_name": "Bernie Raffe AMPA",
        "meta": {
            "all_keywords": ["beginner", "intermediate", "arts", "photography", "digital_photography"],
            "approval_state": "approved",
            "canonical_category": "photography",
            "comments": 3,
            "has_free_promo": false,
            "has_unpublished_changes": true,
            "is_conversation": false,
            "is_third_party_content": false,
            "loves": 4,
            "points": 3,
            "price": 99,
            "project_submissions": 12,
            "published": true,
            "students": 205,
            "views": 364,
            "alt_image_url": null,
            "attachments": 0,
            "card_image_url": "/system/development/files/52681/card/sun.jpg?1429289950",
            "clipped_intro_resource_url": "/system/development/files/27318/original/BernieRaffeAMPA-SunAndShade-00-Intro-v1.mov?1382767284",
            "duration": 372417,
            "exercises": 1,
            "longDescriptionHTML": "Traditional wisdom says to shoot photos with the light behind the camera on a bright and sunny day. While this makes for a more generously lit subject, it does not account for a third alternative: shooting in the shade. In this lesson, Bernie Raffe demonstrates how shade protects against harsh shadows and reveals how to avoid blue skies turning white in your photos. Remember: scenery, positioning and lighting make a good shot.",
            "name": "Taking Photos in Sun and Shade",
            "sections": [{"name": "Lesson Intro", "duration": 41160, "exercises": []}, {
                "name": "Sun From Behind",
                "duration": 70800,
                "exercises": []
            }, {
                "name": "In the Shade",
                "duration": 85377,
                "exercises": [{"name": "Harsh Sunlight"}]
            }, {"name": "Blue Skies", "duration": 175080, "exercises": []}],
            "shortDescription": "Traditional wisdom tells you to shoot photos with light behind you on a bright and sunny day; this lesson shows you how to use shade and shoot for blue skies.",
            "small_card_image_url": "/system/development/files/52681/small_card/sun.jpg?1429289950",
            "still_image_large_original_height": 1080,
            "still_image_large_original_width": 1920,
            "still_image_url": "/system/development/files/52681/large_16x9/sun.jpg?1429289950",
            "still_image_url_large_original": "/system/development/files/52681/large_original/sun.jpg?1429289950"
        },
        "author": {
            "id": 23932,
            "first_name": "First23932",
            "display_name": "Bernie Raffe AMPA",
            "teacher_display_name": "Bernie Raffe AMPA",
            "greeting_name": "First23932",
            "username": "bernieraffeampa",
            "param": "bernieraffeampa",
            "title": "Award winning UK photographer",
            "description": "Bernie is a working photographer based in Bedfordshire UK, and has been passionate about photography ever since his parents bought him his first camera when he was just 11 years old (a Kodak Brownie 127)!\r\n\r\nHe's qualified as a photographer to 'Associate' level with both the MPA (Master Photographers Association), and the SWPP (Society of Wedding and Portrait Photographers) in the UK.\r\n\r\nBernie is a guest speaker on cruise ships, and also in demand as a speaker to other professionals and to beginner and keen amateurs at camera clubs...\r\n\r\nHe loves sharing his passion for photography, and has produced a set of films which are more 'project' based than most photography tips that you come across. These entertaining and informative films will demonstrate, without blinding you with science, how you can be a better photographer, taking more creative and dramatic photos that will wow your friends and family.\r\n",
            "avatar": "/system/development/avatars/23932/normal/me_2x2.5.jpg?1374596592",
            "avatar_square": "/system/development/avatars/23932/square/me_2x2.5.jpg?1374596592",
            "avatar_large": "/system/development/avatars/23932/large/me_2x2.5.jpg?1374596592",
            "tip_prompt": ""
        }
    }, {
        "approved": "approved",
        "author_id": 25173,
        "created_at": "2013-11-22T04:36:51Z",
        "draft_version_id": 21090,
        "duration": 280280,
        "first_published_at": "2013-12-13T02:53:15Z",
        "id": 4005,
        "internal_rating": null,
        "name": "How to Play House of the Rising Sun",
        "position": 32,
        "published_at": "2014-04-01T22:06:08Z",
        "published_version_id": 13139,
        "saved_at": "2014-04-02T10:37:20Z",
        "short_name": "How to Play House of the Rising Sun",
        "slug": "how-to-play-house-of-the-rising-sun",
        "updated_at": "2014-08-27T02:05:00Z",
        "presenter_name": "Best Beginner Guitar Lessons",
        "meta": {
            "all_keywords": ["beginner", "music", "guitar_instrument", "guitar_song"],
            "approval_state": "approved",
            "canonical_category": "guitar",
            "comments": 0,
            "has_free_promo": false,
            "has_unpublished_changes": true,
            "is_conversation": false,
            "is_third_party_content": false,
            "loves": 0,
            "points": 2,
            "price": 99,
            "project_submissions": 0,
            "published": true,
            "students": 22,
            "views": 19,
            "alt_image_url": null,
            "attachments": 5,
            "card_image_url": "/system/development/files/30943/card/HouseOfTheRisingSunChords_Thumb.jpg?1429203420",
            "clipped_intro_resource_url": "/system/development/files/30935/original/HouseOfTheRisingSunChords_00_Intro.mov?1385095783",
            "duration": 280280,
            "exercises": 1,
            "longDescriptionHTML": "Ready to learn one of your first songs on the guitar? Best Beginner Guitar Lessons shows you how to play the traditional folk song, \u201cHouse of the Rising Sun,\" popularized by The Animals. The origins of this ballad remain unknown, but many bands have covered it for its simplicity, soul and ominous sound. You'll need to know how to play the following chords: Am, C, D, E and F.",
            "name": "How to Play House of the Rising Sun",
            "sections": [{"name": "Lesson Intro", "duration": 38480, "exercises": []}, {
                "name": "Chords",
                "duration": 108390,
                "exercises": [{"name": "Correct Chords"}]
            }, {"name": "Rhythm", "duration": 133410, "exercises": []}],
            "shortDescription": "Ready to learn one of your first songs on the guitar? Best Beginner Guitar Lessons shows you how to play the traditional folk song, \"House of the Rising Sun.\"",
            "small_card_image_url": "/system/development/files/30943/small_card/HouseOfTheRisingSunChords_Thumb.jpg?1429203420",
            "still_image_large_original_height": 1080,
            "still_image_large_original_width": 1920,
            "still_image_url": "/system/development/files/30943/large_16x9/HouseOfTheRisingSunChords_Thumb.jpg?1429203420",
            "still_image_url_large_original": "/system/development/files/30943/large_original/HouseOfTheRisingSunChords_Thumb.jpg?1429203420"
        },
        "author": {
            "id": 25173,
            "first_name": "First25173",
            "display_name": "Best Beginner Guitar Lessons",
            "teacher_display_name": "Best Beginner Guitar Lessons",
            "greeting_name": "First25173",
            "username": "bestbeginnerguitarlessons",
            "param": "bestbeginnerguitarlessons",
            "title": "Best Beginner Guitar Lessons Online",
            "description": "My name is Sam Lyons and I have taught beginner guitar lessons to young and old alike for over 36 years. \r\n\r\nI have a proven, unique beginner guitar lessons course that is focused on the beginner guitar student that guides you step-by-step in learning how to play the guitar the right way. ",
            "avatar": "/system/development/avatars/25173/normal/MVC-007F.jpgsamguitar.jpg?1375204864",
            "avatar_square": "/system/development/avatars/25173/square/MVC-007F.jpgsamguitar.jpg?1375204864",
            "avatar_large": "/system/development/avatars/25173/large/MVC-007F.jpgsamguitar.jpg?1375204864",
            "tip_prompt": "I hope you are enjoying my best beginner guitar lessons. Your tips are much appreciated.   \r\nSam Lyons"
        }
    }, {
        "approved": "approved",
        "author_id": 43865,
        "created_at": "2014-01-03T23:01:10Z",
        "draft_version_id": 44897,
        "duration": 612559,
        "first_published_at": "2014-01-15T18:27:26Z",
        "id": 4712,
        "internal_rating": null,
        "name": "Crochet Swirl Sun Hat | Pt 1",
        "position": 6,
        "published_at": "2014-11-07T23:37:16Z",
        "published_version_id": 14919,
        "saved_at": "2014-11-07T23:37:27Z",
        "short_name": "Crochet Swirl Sun Hat | Pt 1",
        "slug": "diy-crochet-swirl-sun-hat-pt-1",
        "updated_at": "2015-12-05T00:23:45Z",
        "presenter_name": "The Crochet Zombie",
        "meta": {
            "all_keywords": ["advanced", "intermediate", "fall", "winter", "crafts", "Crocheting", "clothes_making", "accessories"],
            "approval_state": "approved",
            "canonical_category": "clothes-making",
            "comments": 228,
            "has_free_promo": false,
            "has_unpublished_changes": true,
            "is_conversation": false,
            "is_third_party_content": false,
            "loves": 488,
            "points": 5,
            "price": 199,
            "project_submissions": 36,
            "published": true,
            "students": 1757,
            "views": 8837,
            "alt_image_url": "/system/development/files/37718/large_original/The_Crochet_Zombie___DIY_Crochet_Swirl_Sun_Hat___Pt_1.jpg?1429231456",
            "attachments": 5,
            "card_image_url": "/system/development/files/36532/card/01SwirlSun_.Still003.jpg?1429227897",
            "clipped_intro_resource_url": "/system/development/files/36272/original/01SwirlSun__00_Intro.mp4?1388790275",
            "duration": 612559,
            "exercises": 2,
            "longDescriptionHTML": "Want to make the perfect gift for a toddler? In this lesson, part one of a three-part series, learn how to crochet the first few rounds of an adorable baby sun hat with swirl accents. To complete this project, you\u2019ll only need a ball of heavy cotton yarn and a crochet hook. A written version of the pattern with in-depth instructions is attached.",
            "name": "Crochet Swirl Sun Hat | Pt 1",
            "sections": [{"name": "Lesson Intro", "duration": 17490, "exercises": []}, {
                "name": "Materials",
                "duration": 24630,
                "exercises": []
            }, {"name": "Round 1", "duration": 211640, "exercises": [{"name": "Between Clusters"}]}, {
                "name": "Round 2",
                "duration": 186637,
                "exercises": [{"name": "Which Stitch"}]
            }, {"name": "Round 3", "duration": 172162, "exercises": []}],
            "shortDescription": "Looking for the perfect gift for a toddler? In this lesson, part one of a series, learn how to crochet the first three rounds of an adorable baby sun hat.",
            "small_card_image_url": "/system/development/files/36532/small_card/01SwirlSun_.Still003.jpg?1429227897",
            "still_image_large_original_height": 400,
            "still_image_large_original_width": 720,
            "still_image_url": "/system/development/files/36532/large_16x9/01SwirlSun_.Still003.jpg?1429227897",
            "still_image_url_large_original": "/system/development/files/36532/large_original/01SwirlSun_.Still003.jpg?1429227897"
        },
        "author": {
            "id": 43865,
            "first_name": "First43865",
            "display_name": "The Crochet Zombie",
            "teacher_display_name": "The Crochet Zombie",
            "greeting_name": "First43865",
            "username": "thecrochetzombie",
            "param": "thecrochetzombie",
            "title": "Crochet Instructor and Designer",
            "description": "Hi, I am The Crochet Zombie, I am a yarn lover and a designer of crochet items from clothing to decorations and everything in between. I love to be creative and share the things I learn with my friends, fans and family.",
            "avatar": "/system/development/avatars/43865/normal/logo-tcz-square.jpg?1381430861",
            "avatar_square": "/system/development/avatars/43865/square/logo-tcz-square.jpg?1381430861",
            "avatar_large": "/system/development/avatars/43865/large/logo-tcz-square.jpg?1381430861",
            "tip_prompt": ""
        }
    }, {
        "approved": "approved",
        "author_id": 21857,
        "created_at": "2013-08-18T21:31:26Z",
        "draft_version_id": 56288,
        "duration": 641380,
        "first_published_at": "2013-10-19T00:32:19Z",
        "id": 2237,
        "internal_rating": null,
        "name": "How to Make Sun-Dried Kale Chips",
        "position": 7,
        "published_at": "2015-01-27T21:53:48Z",
        "published_version_id": 49082,
        "saved_at": "2015-01-28T03:55:56Z",
        "short_name": "How to Make Sun-Dried Kale Chips",
        "slug": "how-to-make-sun-dried-kale-chips",
        "updated_at": "2015-12-05T00:23:44Z",
        "presenter_name": "Evita Ochel",
        "meta": {
            "all_keywords": ["beginner", "intermediate", "cooking", "recipe", "vegetarian_food", "cooking_technique", "special_diets"],
            "approval_state": "approved",
            "canonical_category": "cooking",
            "comments": 70,
            "has_free_promo": false,
            "has_unpublished_changes": true,
            "is_conversation": false,
            "is_third_party_content": false,
            "loves": 66,
            "points": 5,
            "price": 0,
            "project_submissions": 8,
            "published": true,
            "students": 314,
            "views": 777,
            "alt_image_url": null,
            "attachments": 5,
            "card_image_url": "/system/development/files/17968/card/SundriedKaleChips_Thumb.jpg?1429166699",
            "clipped_intro_resource_url": "/system/development/files/17961/original/SundriedKaleChips_00_Intro.mov?1376864639",
            "duration": 641380,
            "exercises": 5,
            "longDescriptionHTML": "Don't know what to do with your kale? Check out this lesson and learn how to make sun-dried kale chips! Kale chips are wholesome, delicious, and easy to make: just season the kale with your favorite herbs and spices and let the batch soak up the sun for a few hours. This healthy snack incorporates kale into your diet in the crunchiest, tastiest way. ",
            "name": "How to Make Sun-Dried Kale Chips",
            "sections": [{"name": "Lesson Intro", "duration": 26620, "exercises": []}, {
                "name": "Nutrition Benefits",
                "duration": 80530,
                "exercises": [{"name": "Incorporating Kale"}]
            }, {
                "name": "Process Overview",
                "duration": 73380,
                "exercises": [{"name": "Drying Kale"}]
            }, {
                "name": "Prep the Kale",
                "duration": 100220,
                "exercises": [{"name": "Types of Kale"}]
            }, {
                "name": "Seasoning",
                "duration": 151270,
                "exercises": [{"name": "Choice of Seasonings"}]
            }, {"name": "Sun Dry", "duration": 209360, "exercises": [{"name": "Weather"}]}],
            "shortDescription": "Don't know what to do with your kale? Check out this short lesson by Evita Ochel and learn how to make delicious, crunchy sun-dried kale chips! ",
            "small_card_image_url": "/system/development/files/17968/small_card/SundriedKaleChips_Thumb.jpg?1429166699",
            "still_image_large_original_height": 1080,
            "still_image_large_original_width": 1920,
            "still_image_url": "/system/development/files/17968/large_16x9/SundriedKaleChips_Thumb.jpg?1429166699",
            "still_image_url_large_original": "/system/development/files/17968/large_original/SundriedKaleChips_Thumb.jpg?1429166699"
        },
        "author": {
            "id": 21857,
            "first_name": "First21857",
            "display_name": "Evita Ochel",
            "teacher_display_name": "Evita Ochel",
            "greeting_name": "First21857",
            "username": "evitaochel",
            "param": "evitaochel",
            "title": "Optimal Health Teacher",
            "description": "Evita Ochel is a teacher, writer and speaker in the areas of optimal nutrition, natural health, sustainable living, consciousness studies, metaphysics and spirituality. She is a web TV host, editor of six online publications, and author of the book \"Healing & Prevention Through Nutrition.\" Evita is also the founder of the Healthytarian Lifestyle, that is based on fresh thinking, smart eating and mindful living.\r\n\r\nEvita holds an Honors Bachelor of Science degree in the areas of Biology and Psychology, a Bachelor of Education degree specializing in Science, and is certified as a Holistic Nutritionist. Her work includes teaching, writing and researching about the numerous areas of holistic wellness. Her natural health approach focuses on working with the body's innate ability to heal itself, the mind-body connection, as well as the reduction and elimination of toxins from our body and personal environment. Her nutritional approach focuses on wholesome, natural and plant-based nutrition, which is grounded in ancient wisdom and modern scientific research. She lives by being the change she wishes to see, and helps others rise to their highest potential on every level of their being. ",
            "avatar": "/system/development/avatars/21857/normal/Evita-bio.JPG?1373573266",
            "avatar_square": "/system/development/avatars/21857/square/Evita-bio.JPG?1373573266",
            "avatar_large": "/system/development/avatars/21857/large/Evita-bio.JPG?1373573266",
            "tip_prompt": ""
        }
    }, {
        "approved": "approved",
        "author_id": 176414,
        "created_at": "2014-09-04T22:52:30Z",
        "draft_version_id": 51610,
        "duration": 674004,
        "first_published_at": "2014-09-15T14:43:45Z",
        "id": 12602,
        "internal_rating": null,
        "name": "Classic Yoga Sun Salutations",
        "position": 7,
        "published_at": "2015-01-14T18:19:03Z",
        "published_version_id": 39045,
        "saved_at": "2015-01-14T18:19:05Z",
        "short_name": "Classic Yoga Sun Salutations",
        "slug": "classic-yoga-sun-salutations",
        "updated_at": "2015-01-14T18:19:05Z",
        "presenter_name": "Teddy McDonald Yoga",
        "meta": {
            "all_keywords": ["beginner", "intermediate", "fitness", "yoga", "core"],
            "approval_state": "approved",
            "canonical_category": "fitness",
            "comments": 0,
            "has_free_promo": false,
            "has_unpublished_changes": true,
            "is_conversation": false,
            "is_third_party_content": false,
            "loves": 0,
            "points": 6,
            "price": 199,
            "project_submissions": 0,
            "published": true,
            "students": 33,
            "views": 0,
            "alt_image_url": null,
            "attachments": 2,
            "card_image_url": "/system/development/files/95857/card/Yoga_Meditation_Basics_for_the_Golden_Years_-_Lesson_6-_Classic_Sun_Salutation.mov.Still001.jpg?1429462089",
            "clipped_intro_resource_url": null,
            "duration": 674004,
            "exercises": 2,
            "longDescriptionHTML": "The Classic Sun Salutation is the next step for newfound yogis. This yoga exercise lesson involves hip opening, spine lengthening, and other relaxing movements. Take Sun Salutation A to the next level by challenging yourself with this sequence that strengthens your core and increases overall strength and well-being. Remember to breathe and have fun!",
            "name": "Classic Yoga Sun Salutations",
            "sections": [{"name": "Lesson Intro", "duration": 49486, "exercises": []}, {
                "name": "Half Sun Salutation",
                "duration": 175024,
                "exercises": [{"name": "Yoga Concepts"}]
            }, {
                "name": "Sun Salutation Vinyasa Flow",
                "duration": 219034,
                "exercises": [{"name": "Modyfying Poses"}]
            }, {"name": "Classic Sun Salutation Flow", "duration": 184368, "exercises": []}, {
                "name": "Outro",
                "duration": 46092,
                "exercises": []
            }],
            "shortDescription": "The Classic Sun Salutation is the next step for newfound yogis. This yoga exercise lesson involves hip opening, spine lengthening, and other relaxing movements.",
            "small_card_image_url": "/system/development/files/95857/small_card/Yoga_Meditation_Basics_for_the_Golden_Years_-_Lesson_6-_Classic_Sun_Salutation.mov.Still001.jpg?1429462089",
            "still_image_large_original_height": 547,
            "still_image_large_original_width": 972,
            "still_image_url": "/system/development/files/95857/large_16x9/Yoga_Meditation_Basics_for_the_Golden_Years_-_Lesson_6-_Classic_Sun_Salutation.mov.Still001.jpg?1429462089",
            "still_image_url_large_original": "/system/development/files/95857/large_original/Yoga_Meditation_Basics_for_the_Golden_Years_-_Lesson_6-_Classic_Sun_Salutation.mov.Still001.jpg?1429462089"
        },
        "author": {
            "id": 176414,
            "first_name": "First176414",
            "display_name": "Teddy McDonald Yoga",
            "teacher_display_name": "Teddy McDonald Yoga",
            "greeting_name": "First176414",
            "username": "teddymcdonaldyoga",
            "param": "teddymcdonaldyoga",
            "title": "Yoga Teacher, Adventurer, Happiness Enhancer",
            "description": "",
            "avatar": "/system/development/avatars/176414/normal/ted_running_montgo_spain.JPG?1403308932",
            "avatar_square": "/system/development/avatars/176414/square/ted_running_montgo_spain.JPG?1403308932",
            "avatar_large": "/system/development/avatars/176414/large/ted_running_montgo_spain.JPG?1403308932",
            "tip_prompt": ""
        }
    }, {
        "approved": "approved",
        "author_id": 43865,
        "created_at": "2014-01-06T17:58:41Z",
        "draft_version_id": 54564,
        "duration": 536647,
        "first_published_at": "2014-01-15T18:27:49Z",
        "id": 4747,
        "internal_rating": null,
        "name": "Crochet Swirl Sun Hat | Pt 2",
        "position": 7,
        "published_at": "2015-01-21T22:43:14Z",
        "published_version_id": 44898,
        "saved_at": "2015-01-21T22:43:14Z",
        "short_name": "Crochet Swirl Sun Hat | Pt 2",
        "slug": "diy-crochet-swirl-sun-hat-pt-2",
        "updated_at": "2015-01-21T22:43:14Z",
        "presenter_name": "The Crochet Zombie",
        "meta": {
            "all_keywords": ["advanced", "intermediate", "fall", "winter", "crafts", "Crocheting", "clothes_making", "accessories"],
            "approval_state": "approved",
            "canonical_category": "clothes-making",
            "comments": 39,
            "has_free_promo": false,
            "has_unpublished_changes": false,
            "is_conversation": false,
            "is_third_party_content": false,
            "loves": 124,
            "points": 4,
            "price": 199,
            "project_submissions": 10,
            "published": true,
            "students": 303,
            "views": 1758,
            "alt_image_url": null,
            "attachments": 4,
            "card_image_url": "/system/development/files/36533/card/01SwirlSun_.Still004.jpg?1429227913",
            "clipped_intro_resource_url": null,
            "duration": 536647,
            "exercises": 3,
            "longDescriptionHTML": "Get your hook and yarn ready! This lesson by The Crochet Zombie, part two of a three-part series, shows you how to crochet rounds 4-14 of an adorable sun hat for toddlers with swirl accents. Once these rounds are finished, all that\u2019s left is the brim! And, as a bonus, learn how to alter this pattern to fit any size.",
            "name": "Crochet Swirl Sun Hat | Pt 2",
            "sections": [{
                "name": "Round 4",
                "duration": 172870,
                "exercises": [{"name": "Reviewing the Pattern"}]
            }, {"name": "Round 5", "duration": 110819, "exercises": [{"name": "Rounds"}]}, {
                "name": "Round 6",
                "duration": 149246,
                "exercises": [{"name": "Increase Rounds"}]
            }, {"name": "Rounds 7-14", "duration": 103712, "exercises": []}],
            "shortDescription": "Get your hook and yarn ready! This lesson shows you how to crochet the last three increase rounds and finish the bulk of an adorable sun hat for toddlers.",
            "small_card_image_url": "/system/development/files/36533/small_card/01SwirlSun_.Still004.jpg?1429227913",
            "still_image_large_original_height": 400,
            "still_image_large_original_width": 720,
            "still_image_url": "/system/development/files/36533/large_16x9/01SwirlSun_.Still004.jpg?1429227913",
            "still_image_url_large_original": "/system/development/files/36533/large_original/01SwirlSun_.Still004.jpg?1429227913"
        },
        "author": {
            "id": 43865,
            "first_name": "First43865",
            "display_name": "The Crochet Zombie",
            "teacher_display_name": "The Crochet Zombie",
            "greeting_name": "First43865",
            "username": "thecrochetzombie",
            "param": "thecrochetzombie",
            "title": "Crochet Instructor and Designer",
            "description": "Hi, I am The Crochet Zombie, I am a yarn lover and a designer of crochet items from clothing to decorations and everything in between. I love to be creative and share the things I learn with my friends, fans and family.",
            "avatar": "/system/development/avatars/43865/normal/logo-tcz-square.jpg?1381430861",
            "avatar_square": "/system/development/avatars/43865/square/logo-tcz-square.jpg?1381430861",
            "avatar_large": "/system/development/avatars/43865/large/logo-tcz-square.jpg?1381430861",
            "tip_prompt": ""
        }
    }, {
        "approved": "approved",
        "author_id": 148347,
        "created_at": "2014-03-21T00:47:01Z",
        "draft_version_id": null,
        "duration": 422570,
        "first_published_at": "2014-03-24T23:54:06Z",
        "id": 6788,
        "internal_rating": null,
        "name": "The Sun & Moon Yoga Poses",
        "position": 1,
        "published_at": "2014-03-24T23:54:06Z",
        "published_version_id": 20068,
        "saved_at": "2014-03-24T23:54:06Z",
        "short_name": "The Sun & Moon Yoga Poses",
        "slug": "the-sun-moon-yoga-poses",
        "updated_at": "2014-09-14T11:40:54Z",
        "presenter_name": "Cool Calm and Collected",
        "meta": {
            "all_keywords": ["beginner", "intermediate", "fitness", "yoga"],
            "approval_state": "approved",
            "canonical_category": "fitness",
            "comments": 2,
            "has_free_promo": false,
            "has_unpublished_changes": false,
            "is_conversation": false,
            "is_third_party_content": false,
            "loves": 3,
            "points": 4,
            "price": 0,
            "project_submissions": 0,
            "published": true,
            "students": 14,
            "views": 5,
            "alt_image_url": null,
            "attachments": 0,
            "card_image_url": "/system/development/files/49853/card/HathaYogaSunAndMoonPose_Thumb.jpg?1429278716",
            "clipped_intro_resource_url": "/system/development/files/49837/original/HathaYogaSunAndMoonPose_00_Intro.mov?1395380774",
            "duration": 422570,
            "exercises": 2,
            "longDescriptionHTML": "Getting your body relaxed, limber, and active will help you weather the early morning commute with a smile. Start your day off right with two relaxing Yoga poses from Cool Calm and Collected. In this lesson, learn the Sun Pose and the Moon Pose. This lesson uses reclined versions of these Hatha Yoga poses to emphasize relaxation without sacrificing proper alignment.",
            "name": "The Sun & Moon Yoga Poses",
            "sections": [{
                "name": "Lesson Intro",
                "duration": 27150,
                "exercises": []
            }, {
                "name": "Savasana & Right Crescent",
                "duration": 84050,
                "exercises": [{"name": "Crescent Alignment"}]
            }, {
                "name": "Left Side & Curling Up",
                "duration": 101610,
                "exercises": [{"name": "Working With Your Body"}]
            }, {
                "name": "Savasana & Left Crescent",
                "duration": 94930,
                "exercises": []
            }, {"name": "Right Side & Curling Up", "duration": 114830, "exercises": []}],
            "shortDescription": "Start your day off right with two relaxing Yoga poses. In this lesson, learn the Sun Pose and the Moon Pose, which emphasize relaxation with proper alignment.",
            "small_card_image_url": "/system/development/files/49853/small_card/HathaYogaSunAndMoonPose_Thumb.jpg?1429278716",
            "still_image_large_original_height": 1080,
            "still_image_large_original_width": 1920,
            "still_image_url": "/system/development/files/49853/large_16x9/HathaYogaSunAndMoonPose_Thumb.jpg?1429278716",
            "still_image_url_large_original": "/system/development/files/49853/large_original/HathaYogaSunAndMoonPose_Thumb.jpg?1429278716"
        },
        "author": {
            "id": 148347,
            "first_name": "First148347",
            "display_name": "Cool Calm and Collected",
            "teacher_display_name": "Cool Calm and Collected",
            "greeting_name": "First148347",
            "username": "coolcalmandcollected",
            "param": "coolcalmandcollected",
            "title": "Annemaree Rowley",
            "description": "",
            "avatar": "/assets/lessons/avatars/avatar_default_3_normal.jpg",
            "avatar_square": "/assets/lessons/avatars/avatar_default_3_square.jpg",
            "avatar_large": "/assets/lessons/avatars/avatar_default_3_large.jpg",
            "tip_prompt": ""
        }
    }, {
        "approved": "approved",
        "author_id": 1425,
        "created_at": "2012-12-07T22:50:42Z",
        "draft_version_id": 12546,
        "duration": 986760,
        "first_published_at": "2013-12-06T19:24:08Z",
        "id": 224,
        "internal_rating": null,
        "name": "Yoga: The Sun Salutation",
        "position": 2,
        "published_at": "2013-12-06T19:24:08Z",
        "published_version_id": 1163,
        "saved_at": "2013-12-06T19:24:27Z",
        "short_name": "Yoga: The Sun Salutation",
        "slug": "yoga-for-beginners-the-sun-salutation",
        "updated_at": "2015-12-05T00:23:49Z",
        "presenter_name": "Emma Guth",
        "meta": {
            "all_keywords": ["beginner", "intermediate", "fitness", "yoga"],
            "approval_state": "approved",
            "canonical_category": "fitness",
            "comments": 30,
            "has_free_promo": false,
            "has_unpublished_changes": true,
            "is_conversation": false,
            "is_third_party_content": false,
            "loves": 52,
            "points": 8,
            "price": 0,
            "project_submissions": 60,
            "published": true,
            "students": 591,
            "views": 1028,
            "alt_image_url": null,
            "attachments": 0,
            "card_image_url": "/system/development/files/32653/card/yoga2thumb2.png?1429210495",
            "clipped_intro_resource_url": "/system/development/files/1837/original/02GuthYoga_00_Intro_v5.mp4?1355449977",
            "duration": 986760,
            "exercises": 6,
            "longDescriptionHTML": "Learn the yoga positions for one of the most popular yoga movements - the Sun Salute! This online yoga video teaches how to do yoga in a simple and accessible way. The lesson covers the Lunge, Plank, Cobra and Downward Facing Dog and culminates with the Sun Salute. It\u2019s perfect for someone who has never done yoga before or wants to brush up on their basic yoga postures. ",
            "name": "Yoga: The Sun Salutation",
            "sections": [{"name": "Lesson Intro", "duration": 38780, "exercises": []}, {
                "name": "Breathing Warm Up",
                "duration": 45860,
                "exercises": [{"name": "Breathing"}]
            }, {"name": "The Lunge", "duration": 163070, "exercises": [{"name": "Lunge"}]}, {
                "name": "The Plank",
                "duration": 150250,
                "exercises": [{"name": "Plank"}]
            }, {
                "name": "The Cobra",
                "duration": 111530,
                "exercises": [{"name": "Cobra"}]
            }, {
                "name": "Downward Facing Dog",
                "duration": 121230,
                "exercises": [{"name": "Downward Facing Dog"}]
            }, {
                "name": "All Together - The Sun Salutation Series",
                "duration": 340280,
                "exercises": [{"name": "Sun Salutation"}]
            }, {"name": "Sign Off", "duration": 15760, "exercises": []}],
            "shortDescription": "Learn the yoga positions for one of the most popular yoga movements - the Sun Salute! This online yoga video teaches how to do yoga in an accessible way. ",
            "small_card_image_url": "/system/development/files/32653/small_card/yoga2thumb2.png?1429210495",
            "still_image_large_original_height": 474,
            "still_image_large_original_width": 843,
            "still_image_url": "/system/development/files/32653/large_16x9/yoga2thumb2.png?1429210495",
            "still_image_url_large_original": "/system/development/files/32653/large_original/yoga2thumb2.png?1429210495"
        },
        "author": {
            "id": 1425,
            "first_name": "First1425",
            "display_name": "Emma Guth",
            "teacher_display_name": "Emma Guth",
            "greeting_name": "First1425",
            "username": "eguth",
            "param": "eguth",
            "title": "",
            "description": "Emma is an undergraduate student at Stanford University who enjoys practicing and teaching the art of yoga. She is excited to share her passion through her mini-series on beginning yoga. Namaste!",
            "avatar": "/system/development/avatars/1425/normal/emma1.png?1359516062",
            "avatar_square": "/system/development/avatars/1425/square/emma1.png?1359516062",
            "avatar_large": "/system/development/avatars/1425/large/emma1.png?1359516062",
            "tip_prompt": ""
        }
    }, {
        "approved": "approved",
        "author_id": 6356,
        "created_at": "2014-06-07T06:10:27Z",
        "draft_version_id": 27876,
        "duration": 201402,
        "first_published_at": "2014-06-13T15:05:57Z",
        "id": 9676,
        "internal_rating": null,
        "name": "How to Do Vinyasa Sun Salutations",
        "position": 80,
        "published_at": "2014-06-13T15:05:57Z",
        "published_version_id": 27434,
        "saved_at": "2014-06-13T15:26:46Z",
        "short_name": "How to Do Vinyasa Sun Salutations",
        "slug": "how-to-do-vinyasa-sun-salutations",
        "updated_at": "2015-06-05T18:58:12Z",
        "presenter_name": "Sean Vigue Fitness",
        "meta": {
            "all_keywords": ["beginner", "fitness", "yoga"],
            "approval_state": "approved",
            "canonical_category": "fitness",
            "comments": 0,
            "has_free_promo": false,
            "has_unpublished_changes": true,
            "is_conversation": false,
            "is_third_party_content": false,
            "loves": 0,
            "points": 2,
            "price": 99,
            "project_submissions": 0,
            "published": true,
            "students": 13,
            "views": 1,
            "alt_image_url": null,
            "attachments": 1,
            "card_image_url": "/system/development/files/68903/card/Sun_Sal_thumb.png?1429353754",
            "clipped_intro_resource_url": "/system/development/files/68691/original/Sun_Salutation_00_intro_v1.mov?1402075526",
            "duration": 201402,
            "exercises": 2,
            "longDescriptionHTML": "Learning Sun Salutations is a great first step for anyone interested in beginning a yoga practice. The Sun Salutation can be done as a meditation first thing in the morning or as the last thing you do in the evening before bed. In this lesson, learn how to move through the asanas in a vinyasa flow. This style of power yoga  gets the heart pumping and transforms static asanas into a moving meditation.",
            "name": "How to Do Vinyasa Sun Salutations",
            "sections": [{
                "name": "Lesson Intro",
                "duration": 23624,
                "exercises": []
            }, {
                "name": "Up Dog Pose and Back Stretches ",
                "duration": 86553,
                "exercises": []
            }, {
                "name": "Sun Salutation Repetitions",
                "duration": 91225,
                "exercises": [{"name": "Strike a Pose"}, {"name": "Vinyasa Yoga"}]
            }],
            "shortDescription": "Quiet your mind, get your blood pumping, and drift into a mediative state. This vinyasa power yoga sequence focuses on the Sun Salutation asanas.",
            "small_card_image_url": "/system/development/files/68903/small_card/Sun_Sal_thumb.png?1429353754",
            "still_image_large_original_height": 694,
            "still_image_large_original_width": 1236,
            "still_image_url": "/system/development/files/68903/large_16x9/Sun_Sal_thumb.png?1429353754",
            "still_image_url_large_original": "/system/development/files/68903/large_original/Sun_Sal_thumb.png?1429353754"
        },
        "author": {
            "id": 6356,
            "first_name": "First6356",
            "display_name": "Sean Vigue Fitness",
            "teacher_display_name": "Sean Vigue Fitness",
            "greeting_name": "First6356",
            "username": "seanviguefitness",
            "param": "seanviguefitness",
            "title": "Fitness Personality",
            "description": "Florida\u2019s premier Yoga and Pilates instructor. Creator of Pilates Style\u2019s \u201cBest Male Workout of 2011\u2033 Pilates for Men DVD/Download. YouTube's Most Watched Yoga & Pilates Guy! Opera singer and member Actor\u2019s Equity Association. Taught over 5000 Pilates, Yoga, Spinning, and Boot Camp classes and appeared in over 300 workout videos - I LOVE what I do!\r\n\r\nRecently featured in The Washington Post, Fox News, Pilates Style magazine, The Denver Post, Fit Bottomed Girls, YoFitTV.com, MyGeniusTrainer.com, and many more!\r\n\r\nSean Vigue Fitness is a StyleHaul partner.",
            "avatar": "/system/development/avatars/6356/normal/Sean-Applause_avatar.jpg?1366070203",
            "avatar_square": "/system/development/avatars/6356/square/Sean-Applause_avatar.jpg?1366070203",
            "avatar_large": "/system/development/avatars/6356/large/Sean-Applause_avatar.jpg?1366070203",
            "tip_prompt": ""
        }
    }],
    "total_lessons": 63,
    "series": [{
        "approved": "approved",
        "author_id": 43865,
        "background_color": "sky_blue",
        "cover_resource_id": 102297,
        "created_at": "2014-09-24T20:45:43Z",
        "description": "One thing that\u2019s great about crochet projects for infants and toddlers is they\u2019re often very quick to complete! In this three-lesson course from The Crochet Zombie, complete a crochet swirl sun hat for a toddler or baby from start to finish. This easy crochet hat, which includes a brim, makes for a great DIY baby shower or birthday gift, and is hands-down adorable. This course includes a detailed pattern and easy-to-follow, step-by-step instructions. You\u2019ll also get tips on yarn choice.",
        "id": 878,
        "internal_rating": 60,
        "intro_resource_id": null,
        "name": "Toddler Sun Hat Crochet Project",
        "published": true,
        "resource_id": null,
        "reviews_html": null,
        "short_description": "Learn how to crochet an adorable swirl sun hat for a toddler or baby from start to finish. This easy crochet hat, which includes a brim, makes for a great DIY baby shower or birthday gift.",
        "slug": "toddler-sun-hat-crochet-project",
        "updated_at": "2015-08-19T01:20:16Z",
        "price": 1499,
        "test_price": null,
        "retail_price": null,
        "author": {"teacher_display_name": "The Crochet Zombie", "username": "thecrochetzombie"},
        "complete": true,
        "cover_resource": {
            "id": 102297,
            "name": "cover.jpg",
            "description": null,
            "user_id": 43865,
            "file_name": "cover.jpg",
            "store_file_state": "finished",
            "type": "image",
            "width": 720,
            "height": 400
        },
        "lesson_ids": [4712, 4747, 4748],
        "marketable": true,
        "meta": {
            "all_keywords": ["advanced", "intermediate", "fall", "winter", "crafts", "Crocheting", "clothes_making", "accessories"],
            "attachments": 14,
            "canonical_category": null,
            "comments": 288,
            "duration": 1868895,
            "exercises": 7,
            "lessons": 3,
            "loves": 643,
            "points": 15,
            "price": 1499,
            "project_submissions": 57,
            "published": true,
            "savings_amount": 0,
            "savings_percent": 0.0,
            "still_image_large_original_height": 400,
            "still_image_large_original_width": 720,
            "still_image_url_large_original": "/system/development/files/102297/large_original/cover.jpg?1429490674",
            "students": 1793,
            "views": 11486
        },
        "purchase_thumbnail": "/system/development/files/102297/purchase_thumbnail/cover.jpg?1429490674",
        "presenter_name": "The Crochet Zombie"
    }, {
        "approved": "approved",
        "author_id": 21857,
        "background_color": "beach_yellow",
        "cover_resource_id": 142352,
        "created_at": "2014-09-19T23:17:55Z",
        "description": "Eating a healthful, fresh diet is simpler than you think! In this brief course with natural health teacher and writer Evita Ochel, learn several simple, easy-to-prepare recipes. Begin by learning how to make a healthy snack: kale chips! Then learn how to create a tasty lunch spring salad. Finally, make two healthy, raw (and gluten-free!) desserts: strawberry banana mousse pie and no-bake, apple rhubarb cake. By the end of this course, feel more confident preparing healthy meals at home!",
        "id": 819,
        "internal_rating": null,
        "intro_resource_id": null,
        "name": "Delicious Raw Food Dishes  ",
        "published": true,
        "resource_id": null,
        "reviews_html": null,
        "short_description": "Eating a healthful, fresh diet is simpler than you think! In this brief course with natural health teacher and writer Evita Ochel, learn several simple, nutritious, and easy to prepare raw recipes.",
        "slug": "delicious-raw-food-dishes",
        "updated_at": "2015-04-23T20:45:00Z",
        "price": 999,
        "test_price": null,
        "retail_price": null,
        "author": {"teacher_display_name": "Evita Ochel", "username": "evitaochel"},
        "complete": true,
        "cover_resource": {
            "id": 142352,
            "name": "delicious-raw-food-dishes.jpg",
            "description": null,
            "user_id": 21857,
            "file_name": "delicious-raw-food-dishes.jpg",
            "store_file_state": "finished",
            "type": "image",
            "width": 960,
            "height": 653
        },
        "lesson_ids": [2237, 2234, 2205, 2236],
        "marketable": true,
        "meta": {
            "all_keywords": ["beginner", "intermediate", "cooking", "recipe", "vegetarian_food", "cooking_technique", "special_diets", "salad", "vegan_food", "raw_foods", "dessert", "baking", "gluten_free"],
            "attachments": 21,
            "canonical_category": null,
            "comments": 76,
            "duration": 3677350,
            "exercises": 23,
            "lessons": 4,
            "loves": 67,
            "points": 30,
            "price": 999,
            "project_submissions": 9,
            "published": true,
            "savings_amount": 0,
            "savings_percent": 0.0,
            "still_image_large_original_height": 653,
            "still_image_large_original_width": 960,
            "still_image_url_large_original": "/system/development/files/142352/large_original/delicious-raw-food-dishes.jpg?1429817152",
            "students": 338,
            "views": 853
        },
        "purchase_thumbnail": "/system/development/files/142352/purchase_thumbnail/delicious-raw-food-dishes.jpg?1429817152",
        "presenter_name": "Evita Ochel"
    }, {
        "approved": "approved",
        "author_id": 176414,
        "background_color": "mint_green",
        "cover_resource_id": 142321,
        "created_at": "2014-09-24T16:53:41Z",
        "description": "Ah, the Golden Years: that stage in life when you\u2019re at your wisest\u2014and most likely\u2014not your strongest. Steer clear of a crumpled posture and busy mind with Ted McDonald\u2019s yoga and meditation course. Don\u2019t worry about inflexibility or a short range of motion\u2014Ted offers easy exercises (with modified alternatives) that strengthen and lengthen, while preventing injury and encouraging a relaxed mind. Experience yoga poses, yoga flows, and even a final lesson on meditation\u2014it\u2019s easier than you think.",
        "id": 864,
        "internal_rating": null,
        "intro_resource_id": null,
        "name": "Yoga & Meditation for the Golden Years",
        "published": true,
        "resource_id": null,
        "reviews_html": null,
        "short_description": "Ah, the Golden Years: that stage in life when you\u2019re at your wisest\u2014and most likely\u2014not your strongest. Steer clear of a crumpled posture and busy mind with Ted McDonald\u2019s yoga and meditation course.",
        "slug": "yoga-meditation-for-the-golden-years",
        "updated_at": "2015-04-23T20:44:55Z",
        "price": 1999,
        "test_price": null,
        "retail_price": null,
        "author": {"teacher_display_name": "Teddy McDonald Yoga", "username": "teddymcdonaldyoga"},
        "complete": true,
        "cover_resource": {
            "id": 142321,
            "name": "yoga-meditation-for-the-golden-years.jpg",
            "description": null,
            "user_id": 176414,
            "file_name": "yoga-meditation-for-the-golden-years.jpg",
            "store_file_state": "finished",
            "type": "image",
            "width": 960,
            "height": 420
        },
        "lesson_ids": [11811, 12040, 12039, 12116, 12290, 12602, 12539, 12540, 12804, 12805, 12830],
        "marketable": true,
        "meta": {
            "all_keywords": ["yoga", "fitness", "health", "beginner", "stretching", "intermediate", "core", "meditation"],
            "attachments": 21,
            "canonical_category": null,
            "comments": 0,
            "duration": 8332327,
            "exercises": 37,
            "lessons": 11,
            "loves": 2,
            "points": 71,
            "price": 1999,
            "project_submissions": 0,
            "published": true,
            "savings_amount": 90,
            "savings_percent": 4.30828147438966,
            "still_image_large_original_height": 420,
            "still_image_large_original_width": 960,
            "still_image_url_large_original": "/system/development/files/142321/large_original/yoga-meditation-for-the-golden-years.jpg?1429817088",
            "students": 38,
            "views": 99
        },
        "purchase_thumbnail": "/system/development/files/142321/purchase_thumbnail/yoga-meditation-for-the-golden-years.jpg?1429817088",
        "presenter_name": "Teddy McDonald Yoga"
    }, {
        "approved": "approved",
        "author_id": 224139,
        "background_color": "beach_yellow",
        "cover_resource_id": 102034,
        "created_at": "2014-09-26T21:40:15Z",
        "description": "All aboard, for the celestial trip of a lifetime! This course takes you to the great beyond with tips and techniques for navigating your way across the open sea using the ancient art and science of celestial navigation. With this knowledge and your handy sextant, you\u2019ll be able to locate the North Star, find your latitude using only the sun and the horizon, and create precise measurements that can help you if you\u2019re ever without your GPS.",
        "id": 948,
        "internal_rating": null,
        "intro_resource_id": null,
        "name": "Celestial Navigation Training",
        "published": true,
        "resource_id": null,
        "reviews_html": null,
        "short_description": "This course demonstrates how to navigate across the open sea, find the North Star, and determine your latitude using the ancient art and science of celestial navigation. No GPS, no problem!",
        "slug": "celestial-navigation-training",
        "updated_at": "2015-07-22T07:44:11Z",
        "price": 1499,
        "test_price": null,
        "retail_price": null,
        "author": {"teacher_display_name": "Celestial Navigation", "username": "navigationtraining"},
        "complete": true,
        "cover_resource": {
            "id": 102034,
            "name": "5374308475_619de16a0a_b.jpg",
            "description": null,
            "user_id": 224139,
            "file_name": "5374308475_619de16a0a_b.jpg",
            "store_file_state": "finished",
            "type": "image",
            "width": 1024,
            "height": 576
        },
        "lesson_ids": [9398, 9400, 9402, 10168],
        "marketable": true,
        "meta": {
            "all_keywords": ["beginner", "intermediate", "outdoors", "boating", "celestial_navigation", "sailing"],
            "attachments": 13,
            "canonical_category": null,
            "comments": 0,
            "duration": 2247965,
            "exercises": 21,
            "lessons": 4,
            "loves": 0,
            "points": 19,
            "price": 1499,
            "project_submissions": 0,
            "published": true,
            "savings_amount": 0,
            "savings_percent": 0.0,
            "still_image_large_original_height": 576,
            "still_image_large_original_width": 1024,
            "still_image_url_large_original": "/system/development/files/102034/large_original/5374308475_619de16a0a_b.jpg?1429489678",
            "students": 7,
            "views": 11
        },
        "purchase_thumbnail": "/system/development/files/102034/purchase_thumbnail/5374308475_619de16a0a_b.jpg?1429489678",
        "presenter_name": "Celestial Navigation"
    }, {
        "approved": "approved",
        "author_id": 28407,
        "background_color": "soft_blue",
        "cover_resource_id": 34427,
        "created_at": "2014-09-16T22:59:36Z",
        "description": "Are you learning to play ukulele and looking to jam? In this series, uke expert Aaron of Super Ukulele walks you through the chords and strum patterns of a variety of simple, easy to learn songs on ukulele. Follow along to play \u201cWhite Sandy Beach,\u201d a Hawaiian classic by Israel Kamakawiwo'ole, Weezer\u2019s hit \u201cIsland in the Sun,\u201d holiday tunes like \u201cJingle Bells,\u201d and more. Each chord is introduced with a visual diagram, so even novice players can join in to make some great music on ukulele! ",
        "id": 709,
        "internal_rating": null,
        "intro_resource_id": null,
        "name": "Simple Songs for Ukulele Beginners",
        "published": true,
        "resource_id": null,
        "reviews_html": null,
        "short_description": "Are you learning ukulele chords and looking to jam? In this series, Super Ukulele walks you through the chords and strum patterns of a variety of simple, easy to learn songs on ukulele. ",
        "slug": "simple-songs-for-ukulele-beginners",
        "updated_at": "2015-03-07T00:39:36Z",
        "price": 1497,
        "test_price": null,
        "retail_price": null,
        "author": {"teacher_display_name": "Super Ukulele", "username": "superukulele"},
        "complete": true,
        "cover_resource": {
            "id": 34427,
            "name": "Here_Comes_Santa_Claus_thumb2.jpg",
            "description": null,
            "user_id": 28407,
            "file_name": "Here_Comes_Santa_Claus_thumb2.jpg",
            "store_file_state": "finished",
            "type": "image",
            "width": 947,
            "height": 533
        },
        "lesson_ids": [2832, 6333, 3409, 3288, 3382, 3599, 3474, 3469],
        "marketable": true,
        "meta": {
            "all_keywords": ["beginner", "music", "ukulele_instrument", "intermediate", "ukulele_technique", "ukulele_song", "Christmas"],
            "attachments": 14,
            "canonical_category": null,
            "comments": 22,
            "duration": 3775629,
            "exercises": 16,
            "lessons": 8,
            "loves": 30,
            "points": 31,
            "price": 1497,
            "project_submissions": 2,
            "published": true,
            "savings_amount": 0,
            "savings_percent": 0.0,
            "still_image_large_original_height": 533,
            "still_image_large_original_width": 947,
            "still_image_url_large_original": "/system/development/files/34427/large_original/Here_Comes_Santa_Claus_thumb2.jpg?1429220496",
            "students": 220,
            "views": 1793
        },
        "purchase_thumbnail": "/system/development/files/34427/purchase_thumbnail/Here_Comes_Santa_Claus_thumb2.jpg?1429220496",
        "presenter_name": "Super Ukulele"
    }, {
        "approved": "approved",
        "author_id": 64262,
        "background_color": "soft_blue",
        "cover_resource_id": 122663,
        "created_at": "2014-09-25T17:55:56Z",
        "description": "Sometimes, our world just doesn\u2019t cut it. In this course that uses Autodesk 3D modeling software Maya, multimedia artist and teacher Tohm Judson shows you how to create your own solar system! Create all of our solar system\u2019s planets, complete with realistic textures, then animate the planets in orbit around the sun! Add finishing touches with the NURBS Primitives and Particle Emitter to create a realistic asteroid belt. Finally, light up your solar system using the point source lighting tool!",
        "id": 906,
        "internal_rating": null,
        "intro_resource_id": null,
        "name": "Creating a Solar System in Maya",
        "published": true,
        "resource_id": null,
        "reviews_html": null,
        "short_description": "Sometimes, our world just doesn\u2019t cut it. In this course that uses Autodesk 3D modeling software Maya, Tohm Judson shows you how to create your own solar system and animate the planets in orbit!",
        "slug": "creating-a-solar-system-in-maya",
        "updated_at": "2015-02-01T18:49:21Z",
        "price": 999,
        "test_price": null,
        "retail_price": null,
        "author": {"teacher_display_name": "Tohm Judson", "username": "tohmjudson"},
        "complete": true,
        "cover_resource": {
            "id": 122663,
            "name": "TohmJudson-CreatingASolarSystemInMaya-CourseThumb.jpg",
            "description": null,
            "user_id": 64262,
            "file_name": "TohmJudson-CreatingASolarSystemInMaya-CourseThumb.jpg",
            "store_file_state": "finished",
            "type": "image",
            "width": 1920,
            "height": 1080
        },
        "lesson_ids": [4237, 4236, 5257, 5590, 5594],
        "marketable": true,
        "meta": {
            "all_keywords": ["beginner", "intermediate", "Software", "animation", "Maya"],
            "attachments": 3,
            "canonical_category": null,
            "comments": 1,
            "duration": 3172700,
            "exercises": 17,
            "lessons": 5,
            "loves": 2,
            "points": 26,
            "price": 999,
            "project_submissions": 0,
            "published": true,
            "savings_amount": 0,
            "savings_percent": 0.0,
            "still_image_large_original_height": 1080,
            "still_image_large_original_width": 1920,
            "still_image_url_large_original": "/system/development/files/122663/large_original/TohmJudson-CreatingASolarSystemInMaya-CourseThumb.jpg?1429586496",
            "students": 38,
            "views": 169
        },
        "purchase_thumbnail": "/system/development/files/122663/purchase_thumbnail/TohmJudson-CreatingASolarSystemInMaya-CourseThumb.jpg?1429586496",
        "presenter_name": "Tohm Judson"
    }, {
        "approved": "approved",
        "author_id": 85702,
        "background_color": "cool_green",
        "cover_resource_id": 137895,
        "created_at": "2015-02-23T20:14:11Z",
        "description": "New to yoga and don't know where to start? In this introductory course, Ashley from AlchemYoga walks beginners through the breathing practices, postures, and terminology of the Hatha Yoga practice. Learn how to practice Pranayama (breathing) and different styles of Asanas (postures or poses), such as resting and standing poses. This course guides students through breathing exercises, provides instruction for over forty yoga postures, and ends with an easy Sun Salutation yoga flow sequence.",
        "id": 1401,
        "internal_rating": null,
        "intro_resource_id": null,
        "name": "Hatha Yoga for Beginners",
        "published": true,
        "resource_id": null,
        "reviews_html": null,
        "short_description": "New to yoga and don't know where to start? In this introductory course, Ashley from AlchemYoga walks beginners through the breathing practices, postures, and terminology of the Hatha Yoga practice.",
        "slug": "hatha-yoga-for-beginners",
        "updated_at": "2015-03-27T21:35:58Z",
        "price": 1997,
        "test_price": null,
        "retail_price": null,
        "author": {"teacher_display_name": "AlchemYoga", "username": "alchemyoga"},
        "complete": true,
        "cover_resource": {
            "id": 137895,
            "name": "AlchemYoga_HathaYogaforBeginners_CourseThumbnail.jpg",
            "description": null,
            "user_id": 85702,
            "file_name": "AlchemYoga_HathaYogaforBeginners_CourseThumbnail.jpg",
            "store_file_state": "finished",
            "type": "image",
            "width": 1920,
            "height": 1080
        },
        "lesson_ids": [5823, 17832, 17844, 17848, 17850, 17851, 18170, 17852, 17853, 17854, 17924, 17855],
        "marketable": true,
        "meta": {
            "all_keywords": ["yoga", "health", "fitness"],
            "attachments": 15,
            "canonical_category": null,
            "comments": 0,
            "duration": 8001970,
            "exercises": 67,
            "lessons": 12,
            "loves": 0,
            "points": 68,
            "price": 1997,
            "project_submissions": 0,
            "published": true,
            "savings_amount": 0,
            "savings_percent": 0.0,
            "still_image_large_original_height": 1080,
            "still_image_large_original_width": 1920,
            "still_image_url_large_original": "/system/development/files/137895/large_original/AlchemYoga_HathaYogaforBeginners_CourseThumbnail.jpg?1429660517",
            "students": 17,
            "views": 30
        },
        "purchase_thumbnail": "/system/development/files/137895/purchase_thumbnail/AlchemYoga_HathaYogaforBeginners_CourseThumbnail.jpg?1429660517",
        "presenter_name": "AlchemYoga"
    }, {
        "approved": "approved",
        "author_id": 25173,
        "background_color": "grey_purple",
        "cover_resource_id": 99777,
        "created_at": "2014-09-06T19:31:34Z",
        "description": "Looking for some simple songs to play on the guitar? Follow along with Best Beginner Guitar Lessons and discover how to play classic tunes, like Jambalaya, Amazing Grace, and more! Whether you're picking up the instrument for the very first time, or have been playing for a little while, these simple songs will be easy for you to quickly pick up and play. Improve your skills as a guitarist and impress people with these guitar songs for beginners!",
        "id": 500,
        "internal_rating": null,
        "intro_resource_id": null,
        "name": "Guitar Songs for Beginners",
        "published": true,
        "resource_id": null,
        "reviews_html": null,
        "short_description": "Looking for some simple songs to play on the guitar? Follow along with Best Beginner Guitar Lessons and discover how to play classic tunes, like Jambalaya, Amazing Grace, and more!",
        "slug": "guitar-songs-for-beginners",
        "updated_at": "2015-02-01T18:49:00Z",
        "price": 1499,
        "test_price": null,
        "retail_price": null,
        "author": {"teacher_display_name": "Best Beginner Guitar Lessons", "username": "bestbeginnerguitarlessons"},
        "complete": true,
        "cover_resource": {
            "id": 99777,
            "name": "guitar3.jpg",
            "description": null,
            "user_id": 25173,
            "file_name": "guitar3.jpg",
            "store_file_state": "finished",
            "type": "image",
            "width": 1280,
            "height": 720
        },
        "lesson_ids": [2544, 3383, 3352, 3874, 3915, 4005, 2543],
        "marketable": true,
        "meta": {
            "all_keywords": ["beginner", "music", "guitar_instrument", "guitar_song", "guitar_technique"],
            "attachments": 14,
            "canonical_category": null,
            "comments": 0,
            "duration": 2625880,
            "exercises": 12,
            "lessons": 7,
            "loves": 0,
            "points": 21,
            "price": 1499,
            "project_submissions": 0,
            "published": true,
            "savings_amount": 0,
            "savings_percent": 0.0,
            "still_image_large_original_height": 720,
            "still_image_large_original_width": 1280,
            "still_image_url_large_original": "/system/development/files/99777/large_original/guitar3.jpg?1429478384",
            "students": 30,
            "views": 158
        },
        "purchase_thumbnail": "/system/development/files/99777/purchase_thumbnail/guitar3.jpg?1429478384",
        "presenter_name": "Best Beginner Guitar Lessons"
    }, {
        "approved": "approved",
        "author_id": 25173,
        "background_color": "blue_grey",
        "cover_resource_id": 51468,
        "created_at": "2014-03-25T21:39:38Z",
        "description": "Let\u2019s get real - the point of learning guitar is to play songs! After finishing Sam Lyons\u2019 introductory course on guitar basics and a few simple chords, it\u2019s time to play your first song. In this extensive beginner guitar course, learn all the major chords and a few seventh and minor chords to play a few fun and easy songs on guitar. Rile up the party with a boogie woogie blues-rock rhythm or have a sing-along with one of Hank Williams\u2019 country ballads. After this course, you\u2019ll have a steady repertoire of songs to play on guitar!",
        "id": 223,
        "internal_rating": null,
        "intro_resource_id": null,
        "name": "The Essentials of Guitar | Part 2",
        "published": true,
        "resource_id": null,
        "reviews_html": null,
        "short_description": null,
        "slug": "the-essentials-of-guitar-part-2",
        "updated_at": "2015-02-01T18:48:23Z",
        "price": 2999,
        "test_price": null,
        "retail_price": null,
        "author": {"teacher_display_name": "Best Beginner Guitar Lessons", "username": "bestbeginnerguitarlessons"},
        "complete": true,
        "cover_resource": {
            "id": 51468,
            "name": "guitar3b.jpg",
            "description": null,
            "user_id": 25173,
            "file_name": "guitar3b.jpg",
            "store_file_state": "finished",
            "type": "image",
            "width": 2272,
            "height": 1278
        },
        "lesson_ids": [2691, 2544, 3383, 2548, 2545, 2690, 3352, 3282, 2689, 3905, 2688, 3874, 3875, 3287, 3915, 4005, 2543],
        "marketable": true,
        "meta": {
            "all_keywords": ["beginner", "music", "guitar_instrument", "guitar_technique", "guitar_song"],
            "attachments": 23,
            "canonical_category": null,
            "comments": 0,
            "duration": 6330019,
            "exercises": 36,
            "lessons": 17,
            "loves": 0,
            "points": 51,
            "price": 2999,
            "project_submissions": 0,
            "published": true,
            "savings_amount": 0,
            "savings_percent": 0.0,
            "still_image_large_original_height": 1278,
            "still_image_large_original_width": 2272,
            "still_image_url_large_original": "/system/development/files/51468/large_original/guitar3b.jpg?1429284142",
            "students": 39,
            "views": 257
        },
        "purchase_thumbnail": "/system/development/files/51468/purchase_thumbnail/guitar3b.jpg?1429284142",
        "presenter_name": "Best Beginner Guitar Lessons"
    }, {
        "approved": "approved",
        "author_id": 6356,
        "background_color": "sky_blue",
        "cover_resource_id": 152562,
        "created_at": "2014-08-21T15:42:14Z",
        "description": "Yoga and Pilates each have great health benefits, but together, they form an unbeatable combination. Build focus, flexibility, and core strength with this course! Fitness expert Sean Vigue combines yoga poses from power and vinyasa yoga with Pilates mat exercises to strengthen your stomach, lower back, hips and glutes. Whether you\u2019re an athlete looking to add core work and stretching to your workout routine, or a neophyte looking for a beginner yoga and Pilates class, this is the course for you!",
        "id": 430,
        "internal_rating": null,
        "intro_resource_id": null,
        "name": "Pilates and Yoga for Beginners",
        "published": true,
        "resource_id": null,
        "reviews_html": null,
        "short_description": "The health benefits of Yoga asanas and Pilates exercises form an unbeatable combination! Sean Vigue Fitness displays how to build focus, flexibility, and core strength with beginner Pilates and Yoga.",
        "slug": "pilates-and-yoga-for-beginners",
        "updated_at": "2015-06-05T20:17:48Z",
        "price": 2997,
        "test_price": null,
        "retail_price": null,
        "author": {"teacher_display_name": "Sean Vigue Fitness", "username": "seanviguefitness"},
        "complete": true,
        "cover_resource": {
            "id": 152562,
            "name": "SeanVigueFitness_PilatesandYogaforBeginners_CourseImage.jpg",
            "description": null,
            "user_id": 6356,
            "file_name": "SeanVigueFitness_PilatesandYogaforBeginners_CourseImage.jpg",
            "store_file_state": "finished",
            "type": "image",
            "width": 960,
            "height": 420
        },
        "lesson_ids": [9424, 9493, 1160, 9225, 765, 9366, 9656, 9901, 9668, 9647, 9992, 9530, 9944, 9217, 9506, 9507, 9951, 9676, 9873, 9257, 9996, 9221],
        "marketable": true,
        "meta": {
            "all_keywords": ["beginner", "fitness", "pilates", "intermediate", "workout", "yoga", "stretching", "full_body"],
            "attachments": 10,
            "canonical_category": null,
            "comments": 131,
            "duration": 10446183,
            "exercises": 58,
            "lessons": 22,
            "loves": 227,
            "points": 88,
            "price": 2997,
            "project_submissions": 315,
            "published": true,
            "savings_amount": 0,
            "savings_percent": 0.0,
            "still_image_large_original_height": 420,
            "still_image_large_original_width": 960,
            "still_image_url_large_original": "/system/development/files/152562/large_original/SeanVigueFitness_PilatesandYogaforBeginners_CourseImage.jpg?1433530150",
            "students": 1928,
            "views": 3732
        },
        "purchase_thumbnail": "/system/development/files/152562/purchase_thumbnail/SeanVigueFitness_PilatesandYogaforBeginners_CourseImage.jpg?1433530150",
        "presenter_name": "Sean Vigue Fitness"
    }],
    "total_series": 13
}